# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2029ea01685971f0a9b8924d4067bf71760b3208b2095af5070c44e2e3eeeaddd10b116831dd277619ae4bf1dfba97f6a58c0880b8dbf01f0199039b3a4c883d

test:
  secret_key_base: e1998aa761198e10324d228108cbade3055dea91445529cc363a3200fb0fa6a1bcd4e8440678bd0efc721555679e5e3ad517936e58179345461c0c5907e3c388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
